version: "3"
services:
  back_app:
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=mongodb://db_mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_DATABASE=customer-app
      - MONGO_INITDB_ROOT_USERNAME=bissouni
      - MONGO_INITDB_ROOT_PASSWORD=bissouni
    ports:
      - "27017:27017"

volumes:
  mongodata: 
